### ISSUE TITLE
Question about image license

### ISSUE THREAD

**Issue by stickerlover72** [underdarkskies/Ravencoin-Marketing#32]
Hellow underdarkskies.
I am writing to wonder if I can use the Raven Coin Marketing Images you have created for commercial purposes.

I am investing in Raven coin, and I believe in the value of Raven coin.
I got into the charm of Raven Coin and made a sticker for my notebook.
I am in trouble because people around me ask me to sell stickers.
Please let me know about the license of the images you have created.

I really appreciate you trying for Raven.
Thanks.

**Comment by underdarkskies** [comment]
The copyright of all images exists with their creators, this repository includes some of my personal work and that of many others. Feel free to reach out about specific images. For the most part they are submitted as free use, however i cannot speak to all of them
